SNAPPY rebuild: prefetch GNU tarballs then crossgcc-i386

diff --git a/.github/workflows/build-snappy-coreboot-hp.yml b/.github/workflows/build-snappy-coreboot-hp.yml
--- a/.github/workflows/build-snappy-coreboot-hp.yml
+++ b/.github/workflows/build-snappy-coreboot-hp.yml
@@ -31,9 +31,18 @@ jobs:
             -annotate 0 'HP' \
             -type TrueColor -define bmp:format=bmp3 \
             coreboot/Documentation/coreboot_logo.bmp
-      - name: Host toolchain (skip crossgcc downloads)
+      - name: crossgcc-i386
         run: |
-          sudo apt-get install -y gcc-multilib g++-multilib iasl
+          set -euo pipefail
+          mkdir -p coreboot/util/crossgcc/tarballs
+          cd coreboot/util/crossgcc/tarballs
+          # Prefetch from ftp.gnu.org; ftpmirror.gnu.org failed in this CI.
+          for u in             https://ftp.gnu.org/gnu/gmp/gmp-6.3.0.tar.xz             https://ftp.gnu.org/gnu/mpfr/mpfr-4.2.1.tar.xz             https://ftp.gnu.org/gnu/mpc/mpc-1.3.1.tar.xz             https://ftp.gnu.org/gnu/gcc/gcc-14.2.0/gcc-14.2.0.tar.xz             https://ftp.gnu.org/gnu/binutils/binutils-2.43.1.tar.xz
+          do
+            wget -nv -c "$u" || wget -nv -c "${u/ftp.gnu.org\/gnu/mirrors.kernel.org\/gnu}"
+          done
+          cd "$GITHUB_WORKSPACE"
+          make -C coreboot crossgcc-i386 CPUS="$(nproc)" BUILDGCC_OPTIONS="--nouse-ada"
       
       - name: Patch snappy defconfig SMBIOS
         run: |
